# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Python dependencies
  - package-ecosystem: poetry
    directory: "/"
    schedule:
      interval: "daily"

  # Used docker images
  - package-ecosystem: 'docker'
    directory: assets/docker/cadvisor
    schedule:
      interval: "weekly"
  - package-ecosystem: 'docker'
    directory: assets/docker/grafana
    schedule:
      interval: "weekly"
  - package-ecosystem: 'docker'
    directory: assets/docker/node-exporter
    schedule:
      interval: "weekly"
  - package-ecosystem: 'docker'
    directory: assets/docker/prometheus
    schedule:
      interval: "weekly"
