- name: Ensure post-install routines are active
  hosts: pbs,pve
  gather_facts: false
  tasks:
    - name: Check for no-nag file
      ansible.builtin.stat:
        path: /etc/apt/apt.conf.d/no-nag-script
      register: no_nag_stat_result

    - name: Ensure post-install script was run
      ansible.builtin.assert:
        that: no_nag_stat_result.stat.exists
        success_msg: Proxmox post-install is active.
        fail_msg: Follow the instructions on
          https://community-scripts.github.io/ProxmoxVE/scripts?id=post-pve-install or
          https://community-scripts.github.io/ProxmoxVE/scripts?id=post-pbs-install to install
          post-installation utilities, including the no-nag automation. Unfortunately, this cannot
          be run unattended. See https://github.com/tteck/Proxmox/discussions/1659 for details.
