mqtt:
  server: tcp://mosquitto:1883

  client_id: mqtt-exporter

  topic_path: +/#

  device_id_regex: "home/(.*?)/(?P<deviceid>.*?)/.*"

  # The MQTT QoS level
  qos: 0

  # Optional: Configures mqtt2prometheus to expect an object containing multiple metrics to be
  # published as the value on an mqtt topic. This is the default.
  object_per_topic_config:
    encoding: JSON

cache:
  timeout: 60m

json_parsing:
  separator: .

metrics:
  - prom_name: mqtt_voltage
    mqtt_name: voltage
    help: Voltage reading
    type: gauge

  - prom_name: mqtt_current
    mqtt_name: current
    help: Current reading
    type: gauge

  - prom_name: mqtt_power
    mqtt_name: apower
    help: Power reading
    type: gauge

  - prom_name: mqtt_output
    mqtt_name: output
    help: Output state
    type: gauge

  - prom_name: mqtt_total_energy
    mqtt_name: aenergy.total
    help: Total energy used in Wh
    type: counter
    # TODO: When updated to next release
    # force_monotonicy: true

  - prom_name: mqtt_temperature
    mqtt_name: temperature.tC
    help: Temperature reading in °C
    type: gauge
    const_labels:
      sensor_type: shelly

  - prom_name: restart_required
    mqtt_name: restart_required
    help: Flag indicating that a restart is required
    type: gauge
