[build-system]
requires = ["uv_build>=0.8.4,<0.9.0"]
build-backend = "uv_build"

[project]
name = "iot"
version = "0.1.0"
requires-python = ">=3.11"

dependencies = ["utils"]

[tool.uv.build-backend]
module-name = "iot"
module-root = ""
