[project]
name = "obsidian"
version = "0.1.0"
requires-python = ">=3.11"

dependencies = [
    "pulumi-cloudflare==5.49.1",
    "pulumi-command>=1.0.2",
    "pulumi-docker>=4.6.1",
    "pulumi-random>=4.18.0",
    "pulumi>=3.153.1",
    "pyyaml>=6.0.1",
    "utils",
]
