- name: Configure NFS share for backups
  hosts: pve
  gather_facts: true
  tasks:
    - name: Query existing NFS share
      ansible.builtin.command: >
        pvesm status --storage backup-nfs
      register: get_nfs_result
      changed_when: false
      check_mode: false
      failed_when: false

    - name: Create NFS share if not yet existing
      when: get_nfs_result.rc != 0
      ansible.builtin.command: >
        pvesm add nfs backup-nfs
        --server={{ backup_nfs.server }}
        --export={{ backup_nfs.export }}
        --options={{ backup_nfs.options }}
        --content backup
      check_mode: false
