collections:
  - name: grafana.grafana
    # renovate: datasource=github-releases packageName=grafana/grafana-ansible-collection versioning=semver
    version: 6.1.0
  - name: community.general
    # renovate: datasource=github-releases packageName=ansible-collections/community.general versioning=semver
    version: 12.6.0
