collections:
  - name: grafana.grafana
    # renovate: datasource=github-releases packageName=grafana/grafana-ansible-collection versioning=semver
    version: 5.7.0
  - name: community.general
    # renovate: datasource=github-releases packageName=ansible-collections/community.general versioning=semver
    version: 12.4.0
