collections:
  - name: grafana.grafana
    # renovate: datasource=github-releases packageName=grafana/grafana-ansible-collection versioning=semver
    version: 6.0.6
  - name: community.general
    # renovate: datasource=github-releases packageName=ansible-collections/community.general versioning=semver
    version: 10.4.0
