name: Linters

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4

      - name: Setup project
        uses: ./.github/actions/setup-project
        with:
          # renovate: datasource=github-releases packageName=grafana/alloy versioning=semver
          alloy-version: v1.10.0

      - name: Running checks
        run: |
          uv run pre-commit run --all-files --show-diff-on-failure
